### ISSUE TITLE
Check if `zowe.*Directory` is not nested in `zowe.runtimeDirectory`

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zen#243]
Schema validation is checking, if the directories used for Zowe are valid USS paths. But that's not sufficient, user can define e.g. `zowe.logDirectory`  (or other directories) "inside" `zowe.runtimeDirectory`.
This is not good for couple reasons:
* We recommend to set `zowe.runtimeDirectory` as read-only
* `zwe support` will detect new files when calculating fingerprints
  * This is reported even the original files are fine

Such setting should invoke (at least) a warning:

```yaml
zowe:
  runtimeDirectory: /global/zowe
  logDirectory: /global/zowe/logs
  workspaceDirectory: /global/zowe/workspace
  extensionDirectory: /global/zowe/extensions
```
There are more directories used, like java, node, certificates, but the check for the directories in the example should be fine.
